name: Swift Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: swift test -v
